### ISSUE TITLE
Example of using this Plugin(Server and Client Mode) and Licencing? 

### ISSUE THREAD

**Issue by dsushil2000** [hazelcast/hazelcast-eureka#8]
Can we use this plugin without the HZ Licence?(IDMG)
Also the server and client implementation in Spring Boot with Eureka would be good.

**Comment by mesutcelik** [comment]
Hi @dsushil2000 

Hazelcast IMDG has Apache 2.0 license so feel free to use it.
You can check Eureka based Sample application [here](https://github.com/hazelcast/hazelcast-code-samples/tree/13c48a0983856076bdcbe055f68c2062efaac18e/hazelcast-integration/springboot-eureka-partition-groups).

**Comment by dsushil2000** [comment]
@mesutcelik  Thanks for clarification. I did check above link. It shows the Custom implementation of Eureka Integration using the Discovery SPI. I see this library more close to standards as it provided by IMDG. I would love to have those instructions in readme.

**Comment by mesutcelik** [comment]
Hi @dsushil2000 ,

I probably missed the point. 
Do you want to see a code sample with hazelcast-eureka module instead of custom implementation in this [link](https://github.com/hazelcast/hazelcast-code-samples/tree/v3.9.1/hazelcast-integration/springboot-eureka-partition-groups)?
What kind of instructions do you want to see in README?

You can always send a PR to improve README if you see something missing. It would be appreciated!
